# FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# # 
# WORKDIR /app

# # 
# COPY ./requirements.txt /app/requirements.txt


# #
# RUN pip install --upgrade pip
# RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

# # 
# CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "app.main:app",  "-b", "0.0.0.0:8001", "--log-level", "info", "--reload"]