#!/bin/bash

export ENVIRONMENT='local'
export DB_USERNAME='admin'
export DB_PASSWORD='qAvZfEVBv5KZjPT2JQHY'
export DB_HOST='saju-db-prod.cavrntzv1fhs.ap-northeast-2.rds.amazonaws.com'
export DB_PORT='3306'
export DB_DATABASE='stella_migration_db'
export MONGO_URL=''
export MONGO_DATABASE=''
export MONGO_COLLECTION=''
export REDIS_HOST='localhost'
export REDIS_PORT='6379'
export RABBITMQ_HOST=''
export LOCATION=''
export PRE_DEST=''
export PRE_LANG_DEST=''
export PRE_SPEC_DEST=''
export CURRENT_DEST=''
export CURRENT_LANG_DEST=''
export CURRENT_SPEC_DEST=''
