from sqlalchemy import Column, String, Integer, DateTime, BigInteger
from app.db.session import Base

class MMPPushAppInstall(Base):
    __tablename__ = "mmp_push_app_install"
    
    idx = Column(BigInteger, primary_key=True, autoincrement=True, nullable=False)
    wdate_key = Column(Integer, nullable=False)
    app_name = Column(String, nullable=False)
    app_token = Column(String, nullable=False)
    user_id = Column(String, nullable=False)
    is_orgnic = Column(Integer, nullable=False)
    tracker = Column(String, nullable=False)
    tracker_name = Column(String, nullable=False)
    network_name = Column(String, nullable=False)
    campaign_id = Column(String, nullable=False)
    campaign_name = Column(String, nullable=False)
    adgroup_id = Column(String, nullable=False)
    adgroup_name = Column(String, nullable=False)
    creative_id = Column(String, nullable=False)
    creative_name = Column(String, nullable=True)
    gps_adid = Column(String, nullable=False)
    android_id = Column(String, nullable=False)
    fire_adid = Column(String, nullable=False)
    idfa = Column(String, nullable=False)
    idfa = Column(String, nullable=False)
    idfv = Column(String, nullable=False)
    country = Column(String, nullable=False)
    language = Column(String, nullable=False)
    city = Column(String, nullable=False)
    cost_currency = Column(String, nullable=False)
    postal_code = Column(String, nullable=False)
    device_name = Column(String, nullable=False)
    device_type = Column(String, nullable=False)
    os_name = Column(String, nullable=False)
    store = Column(String, nullable=False)
    platform = Column(String, nullable=False)
    api_level = Column(String, nullable=False)
    sdk_version = Column(String, nullable=False)
    os_version = Column(String, nullable=False)
    timezone = Column(String, nullable=False)
    ip_address = Column(String, nullable=False)
    is_reattributed = Column(Integer, nullable=False, default='')
    created_at = Column(Integer, nullable=False, default='')
    click_time = Column(Integer, nullable=False, default='')
    installed_at = Column(Integer, nullable=False, default='')
    first_tracker = Column(String, nullable=False)
    first_tracker_name = Column(String, nullable=False)
    last_tracker = Column(String, nullable=False)
    last_tracker_name = Column(String, nullable=False)
    click_referer = Column(String, nullable=False)
    referrer = Column(String, nullable=False)
    
   

class MMPPushAppEvent(Base):
    __tablename__ = "mmp_push_app_event"
    
    idx = Column(BigInteger, primary_key=True, autoincrement=True, nullable=False)
    wdate_key = Column(Integer, nullable=False)
    app_name = Column(String, nullable=False)
    app_token = Column(String, nullable=False)
    user_id = Column(String, nullable=False)
    event_name = Column(String, nullable=False)
    is_orgnic = Column(Integer, nullable=False)
    tracker = Column(String, nullable=False)
    tracker_name = Column(String, nullable=False)
    network_name = Column(String, nullable=False)
    campaign_id = Column(String, nullable=False)
    campaign_name = Column(String, nullable=False)
    adgroup_id = Column(String, nullable=False)
    adgroup_name = Column(String, nullable=False)
    creative_id = Column(String, nullable=False)
    creative_name = Column(String, nullable=True)
    gps_adid = Column(String, nullable=False)
    android_id = Column(String, nullable=False)
    fire_adid = Column(String, nullable=False)
    idfa = Column(String, nullable=False)
    idfa = Column(String, nullable=False)
    idfv = Column(String, nullable=False)
    country = Column(String, nullable=False)
    language = Column(String, nullable=False)
    city = Column(String, nullable=False)
    cost_currency = Column(String, nullable=False)
    postal_code = Column(String, nullable=False)
    device_name = Column(String, nullable=False)
    device_type = Column(String, nullable=False)
    os_name = Column(String, nullable=False)
    store = Column(String, nullable=False)
    platform = Column(String, nullable=False)
    api_level = Column(String, nullable=False)
    sdk_version = Column(String, nullable=False)
    os_version = Column(String, nullable=False)
    timezone = Column(String, nullable=False)
    ip_address = Column(String, nullable=False)
    is_reattributed = Column(Integer, nullable=False, default='')
    created_at = Column(Integer, nullable=False, default='')
    click_time = Column(Integer, nullable=False, default='')
    installed_at = Column(Integer, nullable=False, default='')
    first_tracker = Column(String, nullable=False)
    first_tracker_name = Column(String, nullable=False)
    last_tracker = Column(String, nullable=False)
    last_tracker_name = Column(String, nullable=False)
    click_referer = Column(String, nullable=False)
    referrer = Column(String, nullable=False)
    
    