"""create table

Revision ID: db2aae6dfcb6
Revises: 
Create Date: 2023-05-04 10:58:13.298468

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'db2aae6dfcb6'
down_revision = None
branch_labels = None
depends_on = None




def upgrade() -> None:
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('filter', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dummy_data_battle',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('battle_point', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('hash_manager',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('hash_key', sa.VARCHAR(length=500), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('version', 'hash_key')
    )
    op.create_table('loading_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('log_banned',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('log_battle',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('log_date', sa.Integer(), nullable=True),
    sa.Column('uid', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('mode', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('trophy', sa.Integer(), nullable=True),
    sa.Column('crown', sa.Integer(), nullable=True),
    sa.Column('o_nickname', sa.Text(), nullable=True),
    sa.Column('m_deck', sa.Text(), nullable=True),
    sa.Column('o_deck', sa.Text(), nullable=True),
    sa.Column('is_ai', sa.Integer(), nullable=True),
    sa.Column('is_friendly', sa.Integer(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('log_fixed_version',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('app_version', sa.Integer(), nullable=True),
    sa.Column('spec_version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('log_hack_check',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('is_banned', sa.Integer(), nullable=True),
    sa.Column('commend', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('log_hash',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('hash_key', sa.VARCHAR(length=500), nullable=False),
    sa.Column('device_id', sa.VARCHAR(length=500), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('version', 'hash_key', 'device_id')
    )
    op.create_table('log_jackpot',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('server', sa.Integer(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('before_value', sa.Integer(), nullable=True),
    sa.Column('after_Value', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('before_code', sa.Integer(), nullable=True),
    sa.Column('after_code', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('log_login',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('log_date', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('auth_id', sa.Text(), nullable=True),
    sa.Column('auth_platform', sa.Text(), nullable=True),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('hash_key', sa.VARCHAR(length=500), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('log_user_attr',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('coin', sa.Integer(), nullable=True),
    sa.Column('jewel', sa.Integer(), nullable=True),
    sa.Column('stone', sa.Integer(), nullable=True),
    sa.Column('acc_get_jewel', sa.Integer(), nullable=True),
    sa.Column('acc_use_jewel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('log_user_attr_history',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('log_date', sa.Integer(), nullable=True),
    sa.Column('log_hour', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('coin', sa.Integer(), nullable=True),
    sa.Column('jewel', sa.Integer(), nullable=True),
    sa.Column('stone', sa.Integer(), nullable=True),
    sa.Column('at_level', sa.Integer(), nullable=True),
    sa.Column('at_coin', sa.Integer(), nullable=True),
    sa.Column('at_jewel', sa.Integer(), nullable=True),
    sa.Column('at_stone', sa.Integer(), nullable=True),
    sa.Column('acc_get_jewel', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('seq', 'level')
    )
    op.create_table('log_user_data',
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('after_length', sa.Integer(), nullable=True),
    sa.Column('before_length', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('mmp_push_app_event',
    sa.Column('idx', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wdate_key', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.Text(), nullable=False),
    sa.Column('app_token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=False),
    sa.Column('is_orgnic', sa.Integer(), nullable=False),
    sa.Column('tracker', sa.Text(), nullable=False),
    sa.Column('tracker_name', sa.Text(), nullable=False),
    sa.Column('network_name', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.Column('campaign_name', sa.Text(), nullable=False),
    sa.Column('adgroup_id', sa.Text(), nullable=False),
    sa.Column('adgroup_name', sa.Text(), nullable=False),
    sa.Column('creative_id', sa.Text(), nullable=False),
    sa.Column('creative_name', sa.Text(), nullable=True),
    sa.Column('gps_adid', sa.Text(), nullable=False),
    sa.Column('android_id', sa.Text(), nullable=False),
    sa.Column('fire_adid', sa.Text(), nullable=False),
    sa.Column('idfa', sa.Text(), nullable=False),
    sa.Column('idfv', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('cost_currency', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.Text(), nullable=False),
    sa.Column('device_name', sa.Text(), nullable=False),
    sa.Column('device_type', sa.Text(), nullable=False),
    sa.Column('os_name', sa.Text(), nullable=False),
    sa.Column('store', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('api_level', sa.Text(), nullable=False),
    sa.Column('sdk_version', sa.Text(), nullable=False),
    sa.Column('os_version', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=False),
    sa.Column('is_reattributed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('click_time', sa.Integer(), nullable=False),
    sa.Column('installed_at', sa.Integer(), nullable=False),
    sa.Column('first_tracker', sa.Text(), nullable=False),
    sa.Column('first_tracker_name', sa.Text(), nullable=False),
    sa.Column('last_tracker', sa.Text(), nullable=False),
    sa.Column('last_tracker_name', sa.Text(), nullable=False),
    sa.Column('click_referer', sa.Text(), nullable=False),
    sa.Column('referrer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('mmp_push_app_install',
    sa.Column('idx', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wdate_key', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.Text(), nullable=False),
    sa.Column('app_token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('is_orgnic', sa.Integer(), nullable=False),
    sa.Column('tracker', sa.Text(), nullable=False),
    sa.Column('tracker_name', sa.Text(), nullable=False),
    sa.Column('network_name', sa.Text(), nullable=False),
    sa.Column('campaign_id', sa.Text(), nullable=False),
    sa.Column('campaign_name', sa.Text(), nullable=False),
    sa.Column('adgroup_id', sa.Text(), nullable=False),
    sa.Column('adgroup_name', sa.Text(), nullable=False),
    sa.Column('creative_id', sa.Text(), nullable=False),
    sa.Column('creative_name', sa.Text(), nullable=True),
    sa.Column('gps_adid', sa.Text(), nullable=False),
    sa.Column('android_id', sa.Text(), nullable=False),
    sa.Column('fire_adid', sa.Text(), nullable=False),
    sa.Column('idfa', sa.Text(), nullable=False),
    sa.Column('idfv', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('language', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('cost_currency', sa.Text(), nullable=False),
    sa.Column('postal_code', sa.Text(), nullable=False),
    sa.Column('device_name', sa.Text(), nullable=False),
    sa.Column('device_type', sa.Text(), nullable=False),
    sa.Column('os_name', sa.Text(), nullable=False),
    sa.Column('store', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('api_level', sa.Text(), nullable=False),
    sa.Column('sdk_version', sa.Text(), nullable=False),
    sa.Column('os_version', sa.Text(), nullable=False),
    sa.Column('timezone', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.Text(), nullable=False),
    sa.Column('is_reattributed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('click_time', sa.Integer(), nullable=False),
    sa.Column('installed_at', sa.Integer(), nullable=False),
    sa.Column('first_tracker', sa.Text(), nullable=False),
    sa.Column('first_tracker_name', sa.Text(), nullable=False),
    sa.Column('last_tracker', sa.Text(), nullable=False),
    sa.Column('last_tracker_name', sa.Text(), nullable=False),
    sa.Column('click_referer', sa.Text(), nullable=False),
    sa.Column('referrer', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('mobile_language_version',
    sa.Column('platform', sa.VARCHAR(length=500), nullable=False),
    sa.Column('app_version', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('mobile_scenario_language_version',
    sa.Column('platform', sa.VARCHAR(length=500), nullable=False),
    sa.Column('app_version', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('mobile_spec_detail_version',
    sa.Column('platform', sa.VARCHAR(length=500), nullable=False),
    sa.Column('spec', sa.VARCHAR(length=500), nullable=False),
    sa.Column('upload', sa.Integer(), nullable=False),
    sa.Column('publish', sa.Integer(), nullable=False),
    sa.Column('enable', sa.Integer(), nullable=False),
    sa.Column('app_version', sa.Integer(), nullable=False),
    sa.Column('limit_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('platform', 'spec')
    )
    op.create_table('mobile_spec_version',
    sa.Column('platform', sa.VARCHAR(length=500), nullable=False),
    sa.Column('app_version', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('mobile_system_language_version',
    sa.Column('platform', sa.VARCHAR(length=500), nullable=False),
    sa.Column('app_version', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('mobile_version',
    sa.Column('device', sa.VARCHAR(length=500), nullable=False),
    sa.Column('max_version', sa.Integer(), nullable=False),
    sa.Column('min_version', sa.Integer(), nullable=False),
    sa.Column('force_update', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('device')
    )
    op.create_table('network_records',
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('req_origin', sa.Text(), nullable=True),
    sa.Column('status', sa.BigInteger(), nullable=True),
    sa.Column('res_data', sa.Integer(), nullable=True),
    sa.Column('res_final', sa.Integer(), nullable=True),
    sa.Column('latency', sa.BigInteger(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('platform_cache_data',
    sa.Column('platform', sa.VARCHAR(length=500), nullable=False),
    sa.Column('sheet_key', sa.Text(), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('platform')
    )
    op.create_table('platform_pvp_round_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pub_coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pub', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('rewards', sa.Text(), nullable=False),
    sa.Column('issuer', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Integer(), nullable=False),
    sa.Column('expired', sa.DateTime(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retention_tag',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('retention_tag', sa.Text(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('rdate_key', sa.Integer(), nullable=False),
    sa.Column('rdate', sa.DateTime(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('retention_uv',
    sa.Column('rdate_key', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('social_id', sa.Text(), nullable=False),
    sa.Column('platform', sa.Text(), nullable=False),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('ip', sa.Text(), nullable=False),
    sa.Column('rdate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('rdate_key', 'uid')
    )
    op.create_table('spec_chest',
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('raid_type', sa.Text(), nullable=False),
    sa.Column('set_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('seq')
    )
    op.create_table('spec_postbox',
    sa.Column('country', sa.VARCHAR(length=500), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('desc', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('country', 'code')
    )
    op.create_table('spec_raid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maxHp', sa.BigInteger(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('special_postbox',
    sa.Column('special_post_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('server', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=False),
    sa.Column('desc_code', sa.Integer(), nullable=False),
    sa.Column('rewards', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('expire_time', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('special_post_id')
    )
    op.create_table('user_banned',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('expired', sa.DateTime(), nullable=True),
    sa.Column('msg', sa.String(length=1000), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user_banned_device',
    sa.Column('device_id', sa.VARCHAR(length=500), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('user_coupon_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('pub', sa.Text(), nullable=True),
    sa.Column('code', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_currency_0',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_get', sa.BigInteger(), nullable=True),
    sa.Column('daily_use', sa.BigInteger(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_1',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_get', sa.BigInteger(), nullable=True),
    sa.Column('daily_use', sa.BigInteger(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_2',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_get', sa.BigInteger(), nullable=True),
    sa.Column('daily_use', sa.BigInteger(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_3',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_get', sa.BigInteger(), nullable=True),
    sa.Column('daily_use', sa.BigInteger(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_4',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_get', sa.BigInteger(), nullable=True),
    sa.Column('daily_use', sa.BigInteger(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_5',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_get', sa.BigInteger(), nullable=True),
    sa.Column('daily_use', sa.BigInteger(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_6',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_get', sa.BigInteger(), nullable=True),
    sa.Column('daily_use', sa.BigInteger(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_7',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_get', sa.BigInteger(), nullable=True),
    sa.Column('daily_use', sa.BigInteger(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_8',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_get', sa.BigInteger(), nullable=True),
    sa.Column('daily_use', sa.BigInteger(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_9',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('daily_get', sa.BigInteger(), nullable=True),
    sa.Column('daily_use', sa.BigInteger(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_log_0',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('daily_get', sa.Integer(), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_log_1',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('daily_get', sa.Integer(), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_log_2',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('daily_get', sa.Integer(), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_log_3',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('daily_get', sa.Integer(), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_log_4',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('daily_get', sa.Integer(), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_log_5',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('daily_get', sa.Integer(), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_log_6',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('daily_get', sa.Integer(), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_log_7',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('daily_get', sa.Integer(), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_log_8',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('daily_get', sa.Integer(), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_currency_log_9',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=500), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('daily_get', sa.Integer(), nullable=True),
    sa.Column('daily_use', sa.Integer(), nullable=True),
    sa.Column('total_get', sa.BigInteger(), nullable=True),
    sa.Column('total_use', sa.BigInteger(), nullable=True),
    sa.Column('date_key', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'type')
    )
    op.create_table('user_data',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_0',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_1',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_2',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_3',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_4',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_5',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_6',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_7',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_8',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_9',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=500), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('ts', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'category')
    )
    op.create_table('user_data_battle',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('battle_point', sa.BigInteger(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_devices_backup',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('friend_uid', sa.Integer(), nullable=True),
    sa.Column('point', sa.Integer(), nullable=True),
    sa.Column('gift_send', sa.Integer(), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('raid_open', sa.Integer(), nullable=True),
    sa.Column('raid_expire', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_friends_invite',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('friend_uid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_friends_remove',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('friend_uid', sa.Integer(), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_members',
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('server', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('is_nickname', sa.Integer(), nullable=True),
    sa.Column('login_device_id', sa.Text(), nullable=True),
    sa.Column('social_id', sa.Text(), nullable=True),
    sa.Column('is_terms_agree', sa.Integer(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user_payment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('complete', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency_price', sa.Float(), nullable=True),
    sa.Column('currency_code', sa.Text(), nullable=True),
    sa.Column('platform', sa.Text(), nullable=True),
    sa.Column('receipt', sa.Text(), nullable=True),
    sa.Column('target_uid', sa.Integer(), nullable=True),
    sa.Column('social_id', sa.Text(), nullable=True),
    sa.Column('wdate_key', sa.Integer(), nullable=True),
    sa.Column('wdate', sa.DateTime(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_platforms',
    sa.Column('auth_platform', sa.Text(), nullable=True),
    sa.Column('auth_id', sa.Text(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user_platforms_backup',
    sa.Column('auth_platform', sa.Text(), nullable=True),
    sa.Column('auth_id', sa.Text(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user_postbox',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('product_key', sa.Integer(), nullable=True),
    sa.Column('reward_type', sa.Text(), nullable=True),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('reward_count', sa.Integer(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_postbox_0',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_postbox_1',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_postbox_2',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_postbox_3',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_postbox_4',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_postbox_5',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_postbox_6',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_postbox_7',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_postbox_8',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_postbox_9',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('sender_uid', sa.Integer(), nullable=True),
    sa.Column('title_code', sa.Integer(), nullable=True),
    sa.Column('desc_code', sa.Integer(), nullable=True),
    sa.Column('tab', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('rewards', sa.Text(), nullable=True),
    sa.Column('special_reward_id', sa.Integer(), nullable=True),
    sa.Column('is_rewarded', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('expire_time', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    op.create_table('user_raid_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('friend_uid', sa.Integer(), nullable=True),
    sa.Column('friend_nickname', sa.Text(), nullable=True),
    sa.Column('raid_state', sa.Integer(), nullable=True),
    sa.Column('raid_index', sa.Integer(), nullable=True),
    sa.Column('raid_lv', sa.Integer(), nullable=True),
    sa.Column('boss_hp', sa.BigInteger(), nullable=True),
    sa.Column('join_count', sa.Integer(), nullable=True),
    sa.Column('raid_start', sa.Integer(), nullable=True),
    sa.Column('raid_end', sa.Integer(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_rewiew',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('language', sa.Text(), nullable=True),
    sa.Column('purchased', sa.Integer(), nullable=True),
    sa.Column('legend_count', sa.Integer(), nullable=True),
    sa.Column('art_star', sa.Float(), nullable=True),
    sa.Column('fun_star', sa.Float(), nullable=True),
    sa.Column('balance_star', sa.Float(), nullable=True),
    sa.Column('ip', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user_send_gift',
    sa.Column('uid', sa.BigInteger(), nullable=False),
    sa.Column('send_count', sa.Integer(), nullable=True),
    sa.Column('date_key', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('user_server',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('is_base', sa.Integer(), nullable=True),
    sa.Column('server_uid', sa.Integer(), nullable=True),
    sa.Column('server', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'server')
    )
    op.create_table('user_server_backup',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('is_base', sa.Integer(), nullable=True),
    sa.Column('server_uid', sa.Integer(), nullable=True),
    sa.Column('server', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('uid', 'server')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_server_backup')
    op.drop_table('user_server')
    op.drop_table('user_send_gift')
    op.drop_table('user_rewiew')
    op.drop_table('user_raid_result')
    op.drop_table('user_postbox_9')
    op.drop_table('user_postbox_8')
    op.drop_table('user_postbox_7')
    op.drop_table('user_postbox_6')
    op.drop_table('user_postbox_5')
    op.drop_table('user_postbox_4')
    op.drop_table('user_postbox_3')
    op.drop_table('user_postbox_2')
    op.drop_table('user_postbox_1')
    op.drop_table('user_postbox_0')
    op.drop_table('user_postbox')
    op.drop_table('user_platforms_backup')
    op.drop_table('user_platforms')
    op.drop_table('user_payment')
    op.drop_table('user_members')
    op.drop_table('user_friends_remove')
    op.drop_table('user_friends_invite')
    op.drop_table('user_friends')
    op.drop_table('user_devices_backup')
    op.drop_table('user_devices')
    op.drop_table('user_data_battle')
    op.drop_table('user_data_9')
    op.drop_table('user_data_8')
    op.drop_table('user_data_7')
    op.drop_table('user_data_6')
    op.drop_table('user_data_5')
    op.drop_table('user_data_4')
    op.drop_table('user_data_3')
    op.drop_table('user_data_2')
    op.drop_table('user_data_1')
    op.drop_table('user_data_0')
    op.drop_table('user_data')
    op.drop_table('user_currency_log_9')
    op.drop_table('user_currency_log_8')
    op.drop_table('user_currency_log_7')
    op.drop_table('user_currency_log_6')
    op.drop_table('user_currency_log_5')
    op.drop_table('user_currency_log_4')
    op.drop_table('user_currency_log_3')
    op.drop_table('user_currency_log_2')
    op.drop_table('user_currency_log_1')
    op.drop_table('user_currency_log_0')
    op.drop_table('user_currency_9')
    op.drop_table('user_currency_8')
    op.drop_table('user_currency_7')
    op.drop_table('user_currency_6')
    op.drop_table('user_currency_5')
    op.drop_table('user_currency_4')
    op.drop_table('user_currency_3')
    op.drop_table('user_currency_2')
    op.drop_table('user_currency_1')
    op.drop_table('user_currency_0')
    op.drop_table('user_coupon_rewards')
    op.drop_table('user_banned_device')
    op.drop_table('user_banned')
    op.drop_table('special_postbox')
    op.drop_table('spec_raid')
    op.drop_table('spec_postbox')
    op.drop_table('spec_chest')
    op.drop_table('retention_uv')
    op.drop_table('retention_tag')
    op.drop_table('pub_coupons')
    op.drop_table('platform_pvp_round_info')
    op.drop_table('platform_cache_data')
    op.drop_table('network_records')
    op.drop_table('mobile_version')
    op.drop_table('mobile_system_language_version')
    op.drop_table('mobile_spec_version')
    op.drop_table('mobile_spec_detail_version')
    op.drop_table('mobile_scenario_language_version')
    op.drop_table('mobile_language_version')
    op.drop_table('mmp_push_app_install')
    op.drop_table('mmp_push_app_event')
    op.drop_table('log_user_data')
    op.drop_table('log_user_attr_history')
    op.drop_table('log_user_attr')
    op.drop_table('log_login')
    op.drop_table('log_jackpot')
    op.drop_table('log_hash')
    op.drop_table('log_hack_check')
    op.drop_table('log_fixed_version')
    op.drop_table('log_battle')
    op.drop_table('log_banned')
    op.drop_table('loading_images')
    op.drop_table('hash_manager')
    op.drop_table('dummy_data_battle')
    op.drop_table('config')
    # ### end Alembic commands ###


